### ISSUE TITLE
taplo-cli

### ISSUE THREAD

**Issue by drahnr** [TimonPost/cargo-toml-format#1]
Not sure if you're aware of, but a general purpose toml formatter exists. It's rather flexible and I use it for CI already. Might be worth a look :)

**Comment by TimonPost** [comment]
Yes I think ive seen it but not sure if it is specific to Cargo toml files right? Cargo toml has some specific rules. The order of manifest items, the order of package section entries. Specific rules concerning the rustfmt RFC for cargo.toml files etc.. Some of which are supported and some of which I am going to focus more on soon.  Tho, I might be able to use the library version of this crate to remove some of my own formatting code which can be a pain. Tho I will have to see if it provides easier and better control over toml files then toml-edit does.

**Comment by drahnr** [comment]
No, it's a generic toml formatter. But it has a sufficient set of configuration options to get excellent results. Just wanted to note in case you didn't see it, it definitely took me a few search attempts until I stumbled upon it. Link for sake of completeness; https://github.com/tamasfe/taplo

**Comment by TimonPost** [comment]
Yes indeed, it doesnt come up so quick if one searches for 'cargo toml formatter' as its a general toml formatter
